baseURL = 'https://mnkhrmch.github.io/'
languageCode = 'ja'
title = "Manaka's Website"

# ページネーション設定
[pagination]
pagerSize = 20

# Markdownレンダリング設定
[markup.goldmark.renderer]
hardWraps = true
unsafe = true